### ISSUE TITLE
Incompatible with aioamazondevices 15.x: AmazonHttpWrapper now requires save_data (and the 14.2.2 pin breaks core alexa_devices)

### ISSUE THREAD

**Issue by darrenthomas28-lgtm** [d1vanloon/home-assistant-vornado-transom#1]
Thanks for building this — it's the only thing that gets my Transom into Home Assistant, and it's been working well.

Two related problems on recent HA cores, one of which reaches beyond this integration.

## 1. Setup fails with `aioamazondevices` 15.x

On Home Assistant Core 2026.9.1:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 803, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/vornado_transom/__init__.py", line 19, in async_setup_entry
    coordinator = VornadoTransomCoordinator(hass, entry, session)
  File "/config/custom_components/vornado_transom/coordinator.py", line 53, in __init__
    self.client = AlexaSmartHomeClient(...)
  File "/config/custom_components/vornado_transom/alexa/client.py", line 38, in __init__
    self._http = AmazonHttpWrapper(session, self._session_state)
TypeError: AmazonHttpWrapper.__init__() missing 1 required positional argument: 'save_data'
```

The config entry lands in `setup_error`. Worth knowing: **nothing is logged at all** until you enable debug logging on `custom_components.vornado_transom` — so it looks like a silent failure rather than a crash, which cost me a while.

In 15.x the signature is:

```python
AmazonHttpWrapper.__init__(
    client_session: ClientSession,
    session_state_data: AmazonSessionStateData,
    save_data: AmazonSaveDataConfig,
) -> None
```

`AmazonSaveDataConfig` is debug-only — the library touches it in exactly one place, guarded by `if self._save_data.callback:`. With `callback=None` (the default) nothing is ever written to disk, so passing a config with just a path is inert.

Everything else in the integration is already 15.x-compatible: `AmazonSessionStateData`, `AmazonLogin` and `login_mode_stored_data` all have unchanged signatures. This is the only incompatibility.

**Patch that works** — `alexa/client.py`:

```python
from pathlib import Path

from aioamazondevices.structures import AmazonSaveDataConfig
...
        self._http = AmazonHttpWrapper(
            session,
            self._session_state,
            AmazonSaveDataConfig(path=Path("/config")),
        )
```

plus `manifest.json` → `"aioamazondevices==15.1.0"`. Verified working on 2026.9.1: the fan loads and controls normally.

## 2. The `14.2.2` pin silently breaks Home Assistant's own `alexa_devices` integration

This is the part I'd flag as more urgent than the fan.

HA installs `custom_components` requirements at **every startup**, so the `aioamazondevices==14.2.2` pin downgrades the library on every boot. Core's own `alexa_devices` integration requires 15.1.0 as of 2026.9, and fails to import against 14.2.2:

```
ImportError: cannot import name 'NoOnlineDevicesError' from 'aioamazondevices.exceptions'
```

In my case that took out **20 devices / 257 entities** — every Echo, Fire TV and speaker group in the house — and it presents with no log line, `reason: None`, no Reconfigure option, and `Invalid handler specified` if you delete and try to re-add. Nothing points at this integration.

So on any recent core, installing this integration disables stock Alexa as a side effect. That seems worth fixing even if the fan side were fine.

## Would a PR help?

Happy to open one for the `save_data` argument and the manifest bump if that's useful — it's a three-line change. Just say the word.

Environment: HA Core 2026.9.1, HAOS, integration v0.1.0.
